http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths:
      - '/api/*'
  rest:
    host: localhost
    paths:
      - '/login'
      - '/login/*'
      - '/logout'
      - '/exchange'
      - '/exchange/*'

  graphql:
    host: localhost
    paths:
      - '/graphql'
serviceEndpoints:
  rest:
    url: 'http://localhost:8001'

  graphql:
    url: 'http://localhost:4000'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  api:
    apiEndpoints:
      - api
    policies:
      - log:
        - action:
            message: ${req.method} ${req.originalUrl}
      - cors:
        - origin: false
      - proxy:
          - action:
              serviceEndpoint: rest
              changeOrigin: true  

  graphql:
    apiEndpoints:
      - graphql
    policies:
      - log:
        - action:
            message: ${req.method} ${req.originalUrl}
      - cors:
        - origin: false
      - proxy:
          - action:
              serviceEndpoint: graphql
              changeOrigin: true
